imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~


# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

vich_uploader:
    db_driver: orm
    mappings:
        chain_logo:
            uri_prefix: /uploads/images/logo
            upload_destination: %kernel.root_dir%/../www/uploads/images/logo
        discount_img:
            uri_prefix: /uploads/images/discount/img
            upload_destination: %kernel.root_dir%/../www/uploads/images/discount/img
        photo_pizzeria:
            uri_prefix: /uploads/images/pizzeria/photos
            upload_destination: %kernel.root_dir%/../www/uploads/images/pizzeria/photos
        feature:
            uri_prefix: /uploads/images/features
            upload_destination: %kernel.root_dir%/../www/uploads/images/features
        ingredient:
            uri_prefix: /uploads/images/ingredient
            upload_destination: %kernel.root_dir%/../www/uploads/images/ingredient
        photo_pizzeria_delivery:
            uri_prefix: /uploads/images/pizzeria/delivery
            upload_destination: %kernel.root_dir%/../www/uploads/images/pizzeria/delivery
        publication_image:
            uri_prefix: /uploads/images/publication
            upload_destination: %kernel.root_dir%/../www/uploads/images/publication
        slider_image:
            uri_prefix: /uploads/images/slider
            upload_destination: %kernel.root_dir%/../www/uploads/images/slider

avalanche_imagine:
    source_root:  %kernel.root_dir%/../www
    web_root:     %kernel.root_dir%/../www
    cache_prefix: media/cache
    driver:       gd
    filters:
        publication_page:
            type:    relative_resize
            options: { widen: 626, mode: outbound }
        publication_list:
            type:    relative_resize
            options: { heighten: 125, mode: outbound}
        publication_index:
            type:    relative_resize
            options: { heighten: 117, mode: outbound }
        chain_recommend:
            type:    relative_resize
            options: { heighten: 70, mode: outbound }
        chain_list:
            type:    relative_resize
            options: { heighten: 46, mode: outbound }
        chain_top:
            type:    relative_resize
            options: { heighten: 14, mode: outbound }
        chain_header:
            type:    relative_resize
            options: { heighten: 35, mode: outbound }
        chain_page:
            type:    relative_resize
            options: { widen: 175, mode: outbound }
        chain_branch_page:
            type:    relative_resize
            options: { widen: 88, mode: outbound }
        discount_index:
            type:    relative_resize
            options: { heighten: 117, mode: outbound }
        discount_list:
            type:    relative_resize
            options: { heighten: 127, mode: outbound }
        discount_page:
            type:    relative_resize
            options: { widen: 596, mode: outbound }


knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

stfalcon_tinymce:
    include_jquery: true
    tinymce_jquery: true
    selector: ".tinymce"
    tinymce_buttons:
        stfalcon: # Id of the first button
            title: "Stfalcon"
            image: "http://stfalcon.com/favicon.ico"
    theme:
        # Simple theme: same as default theme
#        simple: ~
        # Advanced theme with almost all enabled plugins
#        advanced:
#             plugins:
#                 - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
#                 - "searchreplace wordcount visualblocks visualchars code fullscreen"
#                 - "insertdatetime media nonbreaking save table contextmenu directionality"
#                 - "emoticons template paste textcolor"
#             toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
#             toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
#             image_advtab: true
#             templates:
#                 - {title: 'Test template 1', content: 'Test 1'}
#                 - {title: 'Test template 2', content: 'Test 2'}
        # BBCode tag compatible theme (see http://www.bbcode.org/reference.php)
        bbcode:
             plugins: ["code, link, preview, image, code"]
#             menubar: false
#             toolbar1: "bold,italic,underline,undo,redo,link,unlink,removeformat,cleanup,code,preview"